<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Microsoft.Extensions.Documents</RootNamespace>
    <Description>Unit tests for Microsoft.Extensions.Documents.Abstractions.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Libraries\Microsoft.Extensions.Documents.Abstractions\Microsoft.Extensions.Documents.Abstractions.csproj" ProjectUnderTest="true" />
  </ItemGroup>
</Project>
