// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.AI;
using Microsoft.Extensions.Documents;
using Microsoft.Extensions.Logging;
using Microsoft.Shared.Diagnostics;

namespace Microsoft.Extensions.DataIngestion;

/// <summary>Enriches semantic image nodes with descriptions generated by an AI service.</summary>
public sealed class ImageAlternativeTextEnricher : IngestionDocumentProcessor
{
    private readonly EnricherOptions _options;
    private readonly ChatMessage _systemPrompt;
    private readonly ILogger? _logger;

    /// <summary>Initializes a new instance of the <see cref="ImageAlternativeTextEnricher"/> class.</summary>
    public ImageAlternativeTextEnricher(EnricherOptions options)
    {
        _options = Throw.IfNull(options).Clone();
        _systemPrompt = new(ChatRole.System, "For each of the following images, write a detailed alternative text with fewer than 50 words.");
        _logger = _options.LoggerFactory?.CreateLogger<ImageAlternativeTextEnricher>();
    }

    /// <inheritdoc/>
    public override async Task<IngestionDocument> ProcessAsync(IngestionDocument document, CancellationToken cancellationToken = default)
    {
        _ = Throw.IfNull(document);
        DocumentImage[] images = document.Document.Nodes.OfType<DocumentImage>().Where(ShouldProcess).ToArray();
        Dictionary<DocumentNodeId, string> descriptions = [];

        for (int offset = 0; offset < images.Length; offset += _options.BatchSize)
        {
            DocumentImage[] batch = images.Skip(offset).Take(_options.BatchSize).ToArray();
            string[]? generated = await GenerateDescriptionsAsync(batch, cancellationToken).ConfigureAwait(false);
            if (generated is null)
            {
                continue;
            }

            for (int index = 0; index < batch.Length; index++)
            {
                descriptions.Add(batch[index].Id, generated[index]);
            }
        }

        if (descriptions.Count == 0)
        {
            return document;
        }

        IngestionDocument result = new(document.Identifier, new Document(document.Document.Children.Select(node => Rewrite(node, descriptions)).ToArray()));
        foreach (KeyValuePair<string, object?> metadata in document.Metadata)
        {
            result.Metadata.Add(metadata);
        }

        return result;
    }

    private static bool ShouldProcess(DocumentImage image) =>
        !image.Content.IsEmpty && !string.IsNullOrEmpty(image.MediaType) && string.IsNullOrEmpty(image.Description);

    private static DocumentNode Rewrite(DocumentNode node, IReadOnlyDictionary<DocumentNodeId, string> descriptions) =>
        node switch
        {
            DocumentImage image when descriptions.TryGetValue(image.Id, out string? description) =>
                new DocumentImage(
                    image.Id,
                    image.Content.ToArray(),
                    image.MediaType,
                    image.Source,
                    description,
                    image.PageReferences,
                    image.SourceNodeIds),
            DocumentContainer container =>
                new DocumentContainer(
                    container.Id,
                    container.Role,
                    container.Children.Select(child => Rewrite(child, descriptions)).ToArray(),
                    container.PageReferences,
                    container.SourceNodeIds),
            DocumentTable table =>
                new DocumentTable(
                    table.Id,
                    table.RowCount,
                    table.ColumnCount,
                    table.Cells.Select(cell => new DocumentTableCell(
                        cell.Id,
                        cell.RowIndex,
                        cell.ColumnIndex,
                        cell.Content.Select(child => Rewrite(child, descriptions)).ToArray(),
                        cell.RowSpan,
                        cell.ColumnSpan,
                        cell.Role,
                        cell.PageReferences,
                        cell.SourceNodeIds)).ToArray(),
                    table.PageReferences,
                    table.SourceNodeIds),
            _ => node,
        };

    private async Task<string[]?> GenerateDescriptionsAsync(
        IReadOnlyList<DocumentImage> batch,
        CancellationToken cancellationToken)
    {
        List<AIContent> contents = new(batch.Count);
        foreach (DocumentImage image in batch)
        {
            contents.Add(new DataContent(image.Content, image.MediaType!));
        }

        try
        {
            ChatResponse<string[]> response = await _options.ChatClient.GetResponseAsync<string[]>(
                [_systemPrompt, new(ChatRole.User, contents)],
                _options.ChatOptions,
                cancellationToken: cancellationToken).ConfigureAwait(false);

            if (response.Result.Length == contents.Count)
            {
                return response.Result;
            }

            _logger?.UnexpectedResultsCount(response.Result.Length, contents.Count);
        }
#pragma warning disable CA1031 // Enrichment is explicitly best effort.
        catch (Exception ex)
#pragma warning restore CA1031
        {
            _logger?.UnexpectedEnricherFailure(ex);
        }

        return null;
    }
}
